#!/bin/bash
# TernaryBit OS WASM Build Script
# Traceability: v4.0/ROADMAP.md V4-009
#
# Prerequisites:
#   - Emscripten SDK (emsdk)
#   - Run: source /path/to/emsdk/emsdk_env.sh
#
# Usage:
#   ./wasm/build_wasm.sh           # Build WASM module
#   ./wasm/build_wasm.sh --serve   # Build and start test server
#   ./wasm/build_wasm.sh --native  # Build native test binary

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_ROOT/build/wasm"
WASM_SRC="$SCRIPT_DIR/tbos_wasm_main.c"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   TernaryBit OS - WASM Build                                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Create build directory
mkdir -p "$BUILD_DIR"

# Check for --native flag
if [[ "$1" == "--native" ]]; then
    echo -e "${YELLOW}[BUILD] Building native test binary...${NC}"
    gcc -Wall -Wextra -O2 \
        -I"$PROJECT_ROOT/include" \
        "$WASM_SRC" \
        -o "$BUILD_DIR/tbos_wasm_test"
    echo -e "${GREEN}[OK] Native binary: $BUILD_DIR/tbos_wasm_test${NC}"
    echo ""
    echo "Run with: $BUILD_DIR/tbos_wasm_test"
    exit 0
fi

# Check for Emscripten
if ! command -v emcc &> /dev/null; then
    echo -e "${RED}[ERROR] Emscripten (emcc) not found!${NC}"
    echo ""
    echo "Install Emscripten:"
    echo "  git clone https://github.com/emscripten-core/emsdk.git"
    echo "  cd emsdk"
    echo "  ./emsdk install latest"
    echo "  ./emsdk activate latest"
    echo "  source ./emsdk_env.sh"
    echo ""
    echo "Or build native test binary:"
    echo "  $0 --native"
    exit 1
fi

echo -e "${YELLOW}[BUILD] Compiling WASM module...${NC}"
echo "  Source: $WASM_SRC"
echo "  Output: $BUILD_DIR/tbos.js"
echo ""

# Emscripten compilation
emcc "$WASM_SRC" \
    -I"$PROJECT_ROOT/include" \
    -O2 \
    -s WASM=1 \
    -s EXPORTED_FUNCTIONS='["_main","_tbos_init","_tbos_run","_tbos_command","_tbos_get_bcb_magic","_tbos_get_memory_used"]' \
    -s EXPORTED_RUNTIME_METHODS='["ccall","cwrap","UTF8ToString"]' \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s INITIAL_MEMORY=33554432 \
    -s MAXIMUM_MEMORY=134217728 \
    -s MODULARIZE=1 \
    -s EXPORT_NAME='TBOSModule' \
    -s ENVIRONMENT='web' \
    -s NO_EXIT_RUNTIME=1 \
    -o "$BUILD_DIR/tbos.js"

echo -e "${GREEN}[OK] WASM module built successfully${NC}"

# Copy HTML harness
echo -e "${YELLOW}[BUILD] Copying test harness...${NC}"
cp "$SCRIPT_DIR/tbos.html" "$BUILD_DIR/"

# Create integration script
cat > "$BUILD_DIR/tbos_loader.js" << 'EOF'
// TernaryBit OS WASM Loader
// Auto-generated by build_wasm.sh

window.tbosConsoleWrite = function(text) {
    const terminal = document.getElementById('terminal');
    if (terminal) {
        const line = document.createElement('div');
        line.className = 'output-line';
        line.textContent = text;
        terminal.appendChild(line);
        terminal.scrollTop = terminal.scrollHeight;
    }
    console.log('[TBOS]', text);
};

window.tbosConsoleClear = function() {
    const terminal = document.getElementById('terminal');
    if (terminal) terminal.innerHTML = '';
};

window.tbosUpdateMemory = function(usedKb) {
    const el = document.getElementById('memory-used');
    if (el) el.textContent = usedKb;
};

window.tbosSetReady = function(ready) {
    const status = document.getElementById('wasm-status');
    const statusText = document.getElementById('wasm-status-text');
    const input = document.getElementById('command-input');

    if (status) status.className = 'status-dot ' + (ready ? 'ready' : 'loading');
    if (statusText) statusText.textContent = ready ? 'Ready' : 'Loading...';
    if (input) {
        input.disabled = !ready;
        if (ready) input.focus();
    }
};

// Load WASM module
TBOSModule().then(function(Module) {
    window.TBOS = Module;

    // Run initialization
    Module._tbos_run();

    // Set up command input
    const input = document.getElementById('command-input');
    if (input) {
        input.addEventListener('keydown', function(e) {
            if (e.key === 'Enter') {
                const cmd = this.value.trim();
                if (cmd) {
                    // Echo command
                    tbosConsoleWrite('tbos> ' + cmd);

                    // Execute via WASM
                    const cmdPtr = Module.stringToNewUTF8(cmd);
                    Module._tbos_command(cmdPtr);
                    Module._free(cmdPtr);
                }
                this.value = '';
            }
        });
    }

    console.log('[TBOS] WASM module loaded successfully');
}).catch(function(err) {
    console.error('[TBOS] Failed to load WASM module:', err);
    window.tbosConsoleWrite('[ERROR] Failed to load WASM module: ' + err.message);
});
EOF

echo -e "${GREEN}[OK] Test harness ready${NC}"

# Summary
echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Build Complete                                             ║${NC}"
echo -e "${BLUE}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${BLUE}║   Files:                                                     ║${NC}"
echo -e "${BLUE}║     $BUILD_DIR/tbos.js${NC}"
echo -e "${BLUE}║     $BUILD_DIR/tbos.wasm${NC}"
echo -e "${BLUE}║     $BUILD_DIR/tbos.html${NC}"
echo -e "${BLUE}║     $BUILD_DIR/tbos_loader.js${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Start server if requested
if [[ "$1" == "--serve" ]]; then
    echo -e "${YELLOW}[SERVER] Starting test server on http://localhost:8080${NC}"
    echo "Press Ctrl+C to stop"
    echo ""
    cd "$BUILD_DIR"
    python3 -m http.server 8080
fi

echo "To test in browser:"
echo "  cd $BUILD_DIR"
echo "  python3 -m http.server 8080"
echo "  open http://localhost:8080/tbos.html"
