apiVersion: v1
kind: Namespace
metadata:
  name: sundarios
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sundarios-deployment
  namespace: sundarios
  labels:
    app: sundarios
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sundarios
  template:
    metadata:
      labels:
        app: sundarios
    spec:
      containers:
      - name: sundarios
        image: sundarios:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        env:
        - name: SUNDARIOS_PLATFORM
          value: "kubernetes"
        - name: SUNDARIOS_MODE
          value: "cloud"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sundarios-service
  namespace: sundarios
spec:
  selector:
    app: sundarios
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sundarios-ingress
  namespace: sundarios
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - sundarios.example.com
    secretName: sundarios-tls
  rules:
  - host: sundarios.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sundarios-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sundarios-hpa
  namespace: sundarios
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sundarios-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
